// <auto-generated />
namespace Assignment5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddPropertiesToArtistAndAlbum : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPropertiesToArtistAndAlbum));
        
        string IMigrationMetadata.Id
        {
            get { return "202008081824473_AddPropertiesToArtistAndAlbum"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
